all_cards = [
    # --- ENVIRONMENT ---
    {"word": "pollution", "phonetic": "/pəˈluːʃn/", "meaning": "sự ô nhiễm", "example": "Air pollution is a serious problem.", "topic": "environment"},
    {"word": "climate change", "phonetic": "/ˈklaɪmət tʃeɪndʒ/", "meaning": "biến đổi khí hậu", "example": "Climate change affects the whole planet.", "topic": "environment"},
    {"word": "recycling", "phonetic": "/ˌriːˈsaɪklɪŋ/", "meaning": "tái chế", "example": "Recycling reduces waste.", "topic": "environment"},
    {"word": "renewable energy", "phonetic": "/rɪˈnjuːəbl ˈenədʒi/", "meaning": "năng lượng tái tạo", "example": "Solar energy is renewable.", "topic": "environment"},
    {"word": "deforestation", "phonetic": "/ˌdiːˌfɒrɪˈsteɪʃn/", "meaning": "nạn phá rừng", "example": "Deforestation destroys ecosystems.", "topic": "environment"},
    {"word": "biodegradable", "phonetic": "/ˌbaɪəʊdɪˈɡreɪdəbl/", "meaning": "phân hủy sinh học", "example": "Plastic is not biodegradable.", "topic": "environment"},
    {"word": "ecosystem", "phonetic": "/ˈiːkəʊsɪstəm/", "meaning": "hệ sinh thái", "example": "The local ecosystem is very fragile.", "topic": "environment"},
    {"word": "greenhouse effect", "phonetic": "/ˈɡriːnhaʊs ɪˈfekt/", "meaning": "hiệu ứng nhà kính", "example": "CO2 contributes to the greenhouse effect.", "topic": "environment"},
    {"word": "sustainable", "phonetic": "/səˈsteɪnəbl/", "meaning": "bền vững", "example": "We need sustainable development.", "topic": "environment"},
    {"word": "conservation", "phonetic": "/ˌkɒnsəˈveɪʃn/", "meaning": "sự bảo tồn", "example": "Wildlife conservation is essential.", "topic": "environment"},

    # --- TECHNOLOGY ---
    {"word": "artificial intelligence", "phonetic": "/ˌɑːtɪˈfɪʃl ɪnˈtelɪɡəns/", "meaning": "trí tuệ nhân tạo", "example": "AI is changing the world.", "topic": "technology"},
    {"word": "cybersecurity", "phonetic": "/ˌsaɪbəsɪˈkjʊərəti/", "meaning": "an ninh mạng", "example": "Cybersecurity is a top priority.", "topic": "technology"},
    {"word": "innovation", "phonetic": "/ˌɪnəˈveɪʃn/", "meaning": "sự đổi mới", "example": "Innovation drives growth.", "topic": "technology"},
    {"word": "digitalize", "phonetic": "/ˈdɪdʒɪtəlaɪz/", "meaning": "số hóa", "example": "We need to digitalize records.", "topic": "technology"},
    {"word": "automation", "phonetic": "/ˌɔːtəˈmeɪʃn/", "meaning": "tự động hóa", "example": "Automation reduces costs.", "topic": "technology"},
    {"word": "gadget", "phonetic": "/ˈɡædʒɪt/", "meaning": "thiết bị điện tử", "example": "I love new tech gadgets.", "topic": "technology"},
    {"word": "user-friendly", "phonetic": "/ˌjuːzə ˈfrendli/", "meaning": "dễ sử dụng", "example": "The app is user-friendly.", "topic": "technology"},
    {"word": "database", "phonetic": "/ˈdeɪtəbeɪs/", "meaning": "cơ sở dữ liệu", "example": "Data is stored in a database.", "topic": "technology"},
    {"word": "algorithm", "phonetic": "/ˈælɡərɪðəm/", "meaning": "thuật toán", "example": "The algorithm is complex.", "topic": "technology"},
    {"word": "software", "phonetic": "/ˈsɒftweə(r)/", "meaning": "phần mềm", "example": "I updated my software.", "topic": "technology"},

    # --- EDUCATION ---
    {"word": "curriculum", "phonetic": "/kəˈrɪkjələm/", "meaning": "chương trình học", "example": "The curriculum is very broad.", "topic": "education"},
    {"word": "pedagogy", "phonetic": "/ˈpedəɡɒdʒi/", "meaning": "sư phạm", "example": "Effective pedagogy is vital.", "topic": "education"},
    {"word": "literacy", "phonetic": "/ˈlɪtərəsi/", "meaning": "sự biết chữ", "example": "Adult literacy rates are rising.", "topic": "education"},
    {"word": "tuition", "phonetic": "/tjuˈɪʃn/", "meaning": "học phí", "example": "Tuition fees are quite high.", "topic": "education"},
    {"word": "scholarship", "phonetic": "/ˈskɒləʃɪp/", "meaning": "học bổng", "example": "She won a full scholarship.", "topic": "education"},
    {"word": "discipline", "phonetic": "/ˈdɪsəplɪn/", "meaning": "kỷ luật", "example": "Discipline is key to success.", "topic": "education"},
    {"word": "academic", "phonetic": "/ˌækəˈdemɪk/", "meaning": "học thuật", "example": "He had a great academic record.", "topic": "education"},
    {"word": "assignment", "phonetic": "/əˈsaɪnmənt/", "meaning": "bài tập", "example": "I finished my assignment.", "topic": "education"},
    {"word": "interdisciplinary", "phonetic": "/ˌɪntəˌdɪsəˈplɪnəri/", "meaning": "liên ngành", "example": "An interdisciplinary approach.", "topic": "education"},
    {"word": "assessment", "phonetic": "/əˈsesmənt/", "meaning": "đánh giá", "example": "The assessment was difficult.", "topic": "education"},

    # --- HEALTH ---
    {"word": "nutrition", "phonetic": "/njuˈtrɪʃn/", "meaning": "dinh dưỡng", "example": "Good nutrition is essential.", "topic": "health"},
    {"word": "obesity", "phonetic": "/əʊˈbiːsəti/", "meaning": "béo phì", "example": "Obesity is a health risk.", "topic": "health"},
    {"word": "treatment", "phonetic": "/ˈtriːtmənt/", "meaning": "sự điều trị", "example": "The treatment was successful.", "topic": "health"},
    {"word": "vaccination", "phonetic": "/ˌvæksɪˈneɪʃn/", "meaning": "tiêm chủng", "example": "Vaccination prevents diseases.", "topic": "health"},
    {"word": "epidemic", "phonetic": "/ˌepɪˈdemɪk/", "meaning": "dịch bệnh", "example": "An epidemic broke out.", "topic": "health"},
    {"word": "sedentary", "phonetic": "/ˈsedntri/", "meaning": "thụ động (ngồi nhiều)", "example": "A sedentary lifestyle.", "topic": "health"},
    {"word": "immunity", "phonetic": "/ɪˈmjuːnəti/", "meaning": "hệ miễn dịch", "example": "Exercise boosts immunity.", "topic": "health"},
    {"word": "well-being", "phonetic": "/ˈwel biːɪŋ/", "meaning": "tình trạng hạnh phúc", "example": "Mental well-being is important.", "topic": "health"},
    {"word": "chronic", "phonetic": "/ˈkrɒnɪk/", "meaning": "mãn tính", "example": "He suffers from chronic pain.", "topic": "health"},
    {"word": "prevention", "phonetic": "/prɪˈvenʃn/", "meaning": "sự phòng ngừa", "example": "Prevention is better than cure.", "topic": "health"},

    # --- WORK ---
    {"word": "redundancy", "phonetic": "/rɪˈdʌndənsi/", "meaning": "sự dư thừa nhân viên", "example": "The factory announced redundancy.", "topic": "work"},
    {"word": "recruitment", "phonetic": "/rɪˈkruːtmənt/", "meaning": "sự tuyển dụng", "example": "The recruitment process is slow.", "topic": "work"},
    {"word": "negotiation", "phonetic": "/nɪˌɡəʊʃiˈeɪʃn/", "meaning": "sự đàm phán", "example": "Negotiation is an art.", "topic": "work"},
    {"word": "promote", "phonetic": "/prəˈməʊt/", "meaning": "thăng chức", "example": "She was promoted to manager.", "topic": "work"},
    {"word": "colleague", "phonetic": "/ˈkɒliːɡ/", "meaning": "đồng nghiệp", "example": "My colleagues are very helpful.", "topic": "work"},
    {"word": "overtime", "phonetic": "/ˈəʊvətaɪm/", "meaning": "làm thêm giờ", "example": "I worked a lot of overtime.", "topic": "work"},
    {"word": "resignation", "phonetic": "/ˌrezɪɡˈneɪʃn/", "meaning": "sự từ chức", "example": "He handed in his resignation.", "topic": "work"},
    {"word": "entrepreneur", "phonetic": "/ˌɒntrəprəˈnɜː(r)/", "meaning": "doanh nhân", "example": "She is a successful entrepreneur.", "topic": "work"},
    {"word": "deadline", "phonetic": "/ˈdedlaɪn/", "meaning": "hạn chót", "example": "We missed the deadline.", "topic": "work"},
    {"word": "incentive", "phonetic": "/ɪnˈsentɪv/", "meaning": "sự khuyến khích", "example": "Bonuses are great incentives.", "topic": "work"},

    # --- TRAVEL ---
    {"word": "itinerary", "phonetic": "/aɪˈtɪnərəri/", "meaning": "lịch trình", "example": "The itinerary is very busy.", "topic": "travel"},
    {"word": "destination", "phonetic": "/ˌdestɪˈneɪʃn/", "meaning": "điểm đến", "example": "Paris is a top destination.", "topic": "travel"},
    {"word": "accommodation", "phonetic": "/əˌkɒməˈdeɪʃn/", "meaning": "chỗ ở", "example": "We found cheap accommodation.", "topic": "travel"},
    {"word": "souvenir", "phonetic": "/ˌsuːvəˈnɪə(r)/", "meaning": "quà lưu niệm", "example": "I bought a souvenir.", "topic": "travel"},
    {"word": "ecotourism", "phonetic": "/ˈiːkəʊtʊərɪzəm/", "meaning": "du lịch sinh thái", "example": "Ecotourism is popular.", "topic": "travel"},
    {"word": "expedition", "phonetic": "/ˌekspəˈdɪʃn/", "meaning": "cuộc thám hiểm", "example": "An expedition to the Arctic.", "topic": "travel"},
    {"word": "sightseeing", "phonetic": "/ˈsaɪtsiːɪŋ/", "meaning": "tham quan", "example": "We went sightseeing in Rome.", "topic": "travel"},
    {"word": "hospitality", "phonetic": "/ˌhɒspɪˈtæləti/", "meaning": "lòng hiếu khách", "example": "Thank you for your hospitality.", "topic": "travel"},
    {"word": "journey", "phonetic": "/ˈdʒɜːni/", "meaning": "hành trình", "example": "The journey took 10 hours.", "topic": "travel"},
    {"word": "voyage", "phonetic": "/ˈvɔɪɪdʒ/", "meaning": "chuyến đi biển", "example": "A long sea voyage.", "topic": "travel"},

    # --- FOOD ---
    {"word": "cuisine", "phonetic": "/kwɪˈziːn/", "meaning": "ẩm thực", "example": "I love Italian cuisine.", "topic": "food"},
    {"word": "ingredient", "phonetic": "/ɪnˈɡriːdiənt/", "meaning": "nguyên liệu", "example": "Fresh ingredients are best.", "topic": "food"},
    {"word": "vegetarian", "phonetic": "/ˌvedʒəˈteəriən/", "meaning": "người ăn chay", "example": "I am a vegetarian.", "topic": "food"},
    {"word": "beverage", "phonetic": "/ˈbevərɪdʒ/", "meaning": "đồ uống", "example": "Hot beverages are served.", "topic": "food"},
    {"word": "organic", "phonetic": "/ɔːˈɡænɪk/", "meaning": "hữu cơ", "example": "I prefer organic food.", "topic": "food"},
    {"word": "flavor", "phonetic": "/ˈfleɪvə(r)/", "meaning": "hương vị", "example": "It has a spicy flavor.", "topic": "food"},
    {"word": "digest", "phonetic": "/daɪˈdʒest/", "meaning": "tiêu hóa", "example": "Help your body digest.", "topic": "food"},
    {"word": "delicacy", "phonetic": "/ˈdelɪkəsi/", "meaning": "cao lương mỹ vị", "example": "Caviar is a delicacy.", "topic": "food"},
    {"word": "nutritious", "phonetic": "/njuˈtrɪʃəs/", "meaning": "bổ dưỡng", "example": "Apples are very nutritious.", "topic": "food"},
    {"word": "appetite", "phonetic": "/ˈæpɪtaɪt/", "meaning": "sự ngon miệng", "example": "I lost my appetite.", "topic": "food"},

     # --- ART ---
    {"word": "masterpiece", "phonetic": "/ˈmɑːstəpiːs/", "meaning": "kiệt tác", "example": "The Mona Lisa is a masterpiece.", "topic": "art"},
    {"word": "exhibition", "phonetic": "/ˌeksɪˈbɪʃn/", "meaning": "triển lãm", "example": "The art exhibition was great.", "topic": "art"},
    {"word": "portrait", "phonetic": "/ˈpɔːtreɪt/", "meaning": "chân dung", "example": "A beautiful portrait.", "topic": "art"},
    {"word": "sculpture", "phonetic": "/ˈskʌlptʃə(r)/", "meaning": "điêu khắc", "example": "Modern sculptures are cool.", "topic": "art"},
    {"word": "aesthetic", "phonetic": "/iːsˈθetɪk/", "meaning": "thẩm mỹ", "example": "The app has a clean aesthetic.", "topic": "art"},
    {"word": "contemporary", "phonetic": "/kənˈtemprəri/", "meaning": "đương đại", "example": "Contemporary art is bold.", "topic": "art"},
    {"word": "abstract", "phonetic": "/ˈæbstrækt/", "meaning": "trừu tượng", "example": "An abstract painting.", "topic": "art"},
    {"word": "inspiration", "phonetic": "/ˌɪnspəˈreɪʃn/", "meaning": "nguồn cảm hứng", "example": "Nature is my inspiration.", "topic": "art"},
    {"word": "canvas", "phonetic": "/ˈkænvəs/", "meaning": "toan vẽ", "example": "Oil on canvas.", "topic": "art"},
    {"word": "creative", "phonetic": "/kriˈeɪtɪv/", "meaning": "sáng tạo", "example": "Kids are very creative.", "topic": "art"},

    # --- SPORTS ---
    {"word": "competition", "phonetic": "/ˌkɒmpəˈtɪʃn/", "meaning": "sự cạnh tranh", "example": "Tough competition today.", "topic": "sports"},
    {"word": "tournament", "phonetic": "/ˈtʊənəmənt/", "meaning": "giải đấu", "example": "We won the tennis tournament.", "topic": "sports"},
    {"word": "championship", "phonetic": "/ˈtʃæmpiənʃɪp/", "meaning": "chức vô địch", "example": "The world championship.", "topic": "sports"},
    {"word": "athlete", "phonetic": "/ˈæθliːt/", "meaning": "vận động viên", "example": "He is a pro athlete.", "topic": "sports"},
    {"word": "recreation", "phonetic": "/ˌrekriˈeɪʃn/", "meaning": "sự giải trí", "example": "Sports are for recreation.", "topic": "sports"},
    {"word": "endurance", "phonetic": "/ɪnˈdjʊərəns/", "meaning": "sự chịu đựng", "example": "Running needs endurance.", "topic": "sports"},
    {"word": "referee", "phonetic": "/ˌrefəˈriː/", "meaning": "trọng tài", "example": "The referee blew the whistle.", "topic": "sports"},
    {"word": "stadium", "phonetic": "/ˈsteɪdiəm/", "meaning": "sân vận động", "example": "A crowded stadium.", "topic": "sports"},
    {"word": "tactic", "phonetic": "/ˈtæktɪk/", "meaning": "chiến thuật", "example": "We need a new tactic.", "topic": "sports"},
    {"word": "spectator", "phonetic": "/spekˈteɪtə(r)/", "meaning": "khán giả", "example": "The spectators cheered.", "topic": "sports"},

    # --- MEDIA ---
    {"word": "broadcast", "phonetic": "/ˈbrɔːdkɑːst/", "meaning": "phát sóng", "example": "The news is broadcast daily.", "topic": "media"},
    {"word": "journalism", "phonetic": "/ˈdʒɜːnəlɪzəm/", "meaning": "báo chí", "example": "Independent journalism.", "topic": "media"},
    {"word": "advertising", "phonetic": "/ˈædvətaɪzɪŋ/", "meaning": "quảng cáo", "example": "Advertising affects kids.", "topic": "media"},
    {"word": "censorship", "phonetic": "/ˈsensəʃɪp/", "meaning": "sự kiểm duyệt", "example": "Internet censorship.", "topic": "media"},
    {"word": "publication", "phonetic": "/ˌpʌblɪˈkeɪʃn/", "meaning": "sự xuất bản", "example": "A weekly publication.", "topic": "media"},
    {"word": "journalist", "phonetic": "/ˈdʒɜːnəlɪst/", "meaning": "phóng viên", "example": "He is a famous journalist.", "topic": "media"},
    {"word": "mainstream", "phonetic": "/ˈmeɪnstriːm/", "meaning": "chính thống", "example": "Mainstream media coverage.", "topic": "media"},
    {"word": "tabloid", "phonetic": "/ˈtæblɔɪd/", "meaning": "báo lá cải", "example": "Tabloids spread rumors.", "topic": "media"},
    {"word": "coverage", "phonetic": "/ˈkʌvərɪdʒ/", "meaning": "sự đưa tin", "example": "Fair media coverage.", "topic": "media"},
    {"word": "editorial", "phonetic": "/ˌedɪˈtɔːriəl/", "meaning": "bài biên tập", "example": "An insightful editorial.", "topic": "media"}
]
